#ifndef __DESKTOP_POLIMI_PROJECTS_CG_ASTRARACCOONS_HEADERS_GRAPHICS_UNIFORMS_HPP_
#define __DESKTOP_POLIMI_PROJECTS_CG_ASTRARACCOONS_HEADERS_GRAPHICS_UNIFORMS_HPP_

struct GlobalUniforms {

};

struct Uniforms {
    alignas(16) glm::mat4 mvpMat;
};

#endif // __DESKTOP_POLIMI_PROJECTS_CG_ASTRARACCOONS_HEADERS_GRAPHICS_UNIFORMS_HPP_